---
style: Mattel v. MGA
mnemonic: Bratz dolls
plaintiffs:
  - Mattel, Inc.
defendants:
  - MGA Entertainment, Inc.
  - MGA Entertainment (HK) Limited
  - Isaac Larian
  - Carter Bryant
  - Carlos Gustavo Machado Gomez
  - MGAE de Mexico, S.R.L. de C.V.
  - Anne Wang
  - Omni 808 Investors LLC
reports:
  - volume: 616
    reporter: F.3d
    page: 904
tags:
  - Contract
  - Copyright
  - Toy Industry
  - Worker Intellectual Property
  - Idea-Expression Dichotomy
  - Trademark
  - Constructive Trusts
courts:
  - 9th Circuit
numbers:
  - "09-55673"
  - "2:04-cv-09049-SGL-RNB"
documents:
  - date: 2010-07-22
    title: opinion
    author: Kozinski
    panel:
      - Kozinski
      - Trott
      - Wardlaw
notes: |
  - CIAA defined "invesntions" without the word "ideas"
  - CIAA "at any time during my employment by the company" means only during work, within scope of assignments?
