---
style: Bowman v. Monsanto
plaintiffs:
  - Vernon Hugh Bowman
defendants:
  - Monsanto Company
courts:
  - Supreme Court of the United States of America
numbers:
  - 11-796
reports:
  - 569 U.S. 278
tags:
  - Patent
  - Patent Exhaustion
  - First Sale Doctrine
claims:
  - patent infringement
holdings:
  - patent exhaustion doesn't allow farmer to plant and grow saved seeds covered by patent without permission
