---
style: Bowman v. Monsanto
plaintiffs:
  - Vernon Hugh Bowman
defendants:
  - Monsanto Company
courts:
  - Supreme Court
numbers:
  - 11-796
reports:
  - volume: 569
    reporter: U.S.
    page: 278
tags:
  - Patent
  - Patent Exhaustion
  - First Sale Doctrine
claims:
  - Patent Infringement
holdings:
  - patent exhaustion doesn't allow farmer to plant and grow saved seeds covered by patent without permission
