---
style: Bolger v. Amazon
mnemonic: exploding laptop battery
plaintiffs:
  - Angela Bolger
defendants:
  - Amazon.com, LLC
courts:
    - Court of Appeal, Fourth Appellate District, Division One, State of Califofnia
year: 2020
numbers:
  - "37-2017-00003009-CU-PL-CTL"
tags:
  - Section 230
  - Strict Products Liability
notes:
  - exploding laptop battery
holdings:
  - strict product liability
  - CDA 230 does not bar
