---
style: Bolger v. Amazon
mnemonic: exploding laptop battery
plaintiffs:
  - Angela Bolger
defendants:
  - Amazon.com, LLC
year: 2020
numbers:
  California Court of Appeal, Fourth Appellate District, Division 1: "37-2017-00003009-CU-PL-CTL"
tags:
  - Section 230
  - Strict Products Liability
notes: |
  - exploding laptop battery
holdings:
  - strict product liability
  - CDA 230 does not bar
