---
style: DSC v. DGI
plaintiffs:
  - DSC Communications Corp.
defendants:
  - DGI Technologies, Inc.
reports:
  - volume: 81
    reporter: F.3d
    page: 597
courts:
  - 5th Circuit
year: 1996
tags:
  - Copyright
  - Copyright Misuse
  - Software
notes:
  - digital switching system software
holdings:
  - copyright misuse
