---
style: DSC v. DGI
plaintiffs:
  - DSC Communications Corp.
defendants:
  - DGI Technologies, Inc.
reports:
  - 81 F.3d 597
courts:
  - 5th Circuit
year: 1996
tags:
  - Copyright
  - Copyright Misuse
  - Software
notes:
  - digital switching system software
holdings:
  - copyright misuse
