---
style: Ximpleware v. Versata
mnemonic: GPL violation
plaintiffs:
  - Ximpleware
defendants:
  - Versata
courts:
  - Northern District of California
numbers:
  - "5:13-cv-05161"
tags:
  - Copyright
  - Open Source
  - Dual Licensing
  - GPL
