---
style: Ximpleware v. Versata
mnemonic: GPL violation
plaintiffs:
  - Ximpleware
defendants:
  - Versata
numbers:
  N.D. Cal.: "5:13-cv-05161"
tags:
  - Copyright
  - Open Source
  - Dual Licensing
  - GPL
