---
style: MAI v. Peak Computer
plaintiffs:
  - MAI Systems Corp.
defendants:
  - Peak Computer, Inc.
reports:
  - 991 F.2d 511
courts:
  - 9th Circuit
year: 1993
tags:
  - Copyright
  - First Sale Doctrine
  - 17 USC 177
  - MAI Trio
notes:
  - maintenance and repair
holdings:
  - licensed, not "owner" under first sale or 117
