---
style: CoKinetic v. Panasonic Avionics
plaintiffs:
  - CoKinetic Systems Corp.
defendants:
  - Panasonic Avionics Corporation
numbers:
  Southern District of New York: 17-cv-1527
tags:
  - Copyright
  - GPLv2
  - Open Source
  - Free Software
claims:
  - Antitrust
  - Unfair Competition
claims:
  - third-party beneficiary of GPLv2
