---
style: Trump v. Secretary of Pennsylvania
numbers:
  Middle District of Pennsylvania: 20-3371
tags:
  - Election Law
  - 2020 Presidential Election
  - Politics
  - Donald Trump
  - Pennsylvania Law
