---
style: Star Athletica v. Varity Brands
plaintiffs:
  - Star Athletica, LLC
defendants:
  - Varsity Brands, Inc.
courts:
  - Supreme Court
year: 2017
numbers:
  - "15-866"
tags:
  - Intellectual Property
  - Copyright
notes:
  - designs on cheerleading uniforms
holdings:
  - not infringement
  - A feature incorporated into the design of a useful article is eligible for copyright protection only if the feature (1) can be perceived as a two-o or three-dimensional work of art separate from the useful article, and (2) would qualify as a protectable pictorial, graphic, or sculptural work---either on its own or fixed in some other tangible medium of expression---if it were imagined separately from the useful article into which it is incorporated.
