---
style: Jacobsen v. Katzer
mnemonic: model train software
plaintiffs:
  - Robert Jacobsen
defendants:
  - Matthew Katzer
  - Kamind Associates, Inc.
numbers:
  Northern District of California: 3:06-cv-01905-JSW
tags:
  - Open Source
  - Artistic License
  - Copyright
  - License or Contract
reports:
  - volume: 609
    reporter: F.Supp.2d
    page: 925
  - volume: 535
    reporter: F.3d
    page: 1373
