#!/usr/bin/env ruby
require 'yaml'
require 'cgi'

cases = Array.new
tags = Hash.new

Dir.glob '**/meta.yml' do |file|
  data = YAML.load_file(file)
  id = File.dirname(file)
  record = { :id => id, :style => data['style'] }
  cases.push(record)
  data['tags'].each do |tag|
    tags[tag] = [] if tags[tag].nil?
    tags[tag].push(record)
  end
end

def escape(string)
  return CGI::escape_html(string)
end

cases.sort_by { |i| i[:style] }

File.open('index.html', 'w') do |f|
  f.write <<EOS
<!doctype html>
<html lang=en-US>
  <head>
    <meta charset=UTF-8>
    <meta name=viewport content="width=device-width, initial-scale=1">
    <title>Cases</title>
  </head>
  <body>
EOS
  # Case List
  f.write("<h2 id=cases>Cases</h2>\n")
  f.write("<ul>\n")
  cases.each do |record|
    f.write("<li><a href=#{record[:id]}>#{escape(record[:style])}</a></li>\n")
  end
  f.write("</ul>\n")

  # Tag Index
  f.write("<h2 id=tags>Tags</h2>\n")
  tags.sort.each do |tag, records|
    id = tag.downcase.gsub(/ /, '-').gsub(/[^A-Za-z0-9-]/, '')
    f.write("<h3 id=\"#{id}\">#{escape(tag)}</h3>")
    f.write("<ul>")
    records.sort_by { |i| i[:style] }
    records.each do |record|
      f.write("<li><a href=#{record[:id]}>#{escape(record[:style])}</a></li>\n")
    end
    f.write("</ul>")
  end
  f.write("</body>")
  f.write("</html>")
end
