---
style: Blizzard v. Lilith Games
plaintiffs:
  - Blizzard Entertainment, Inc.
defendants:
  - Lilith Games (Shanghai) Co. Ltd.
  - UCool, Inc.
courts:
  - Northern District of California
numbers:
  - "3:2015cv04084"
tags:
  - Copyright
  - Open Source
