---
style: Blizzard v. Lilith Games
plaintiffs:
  - Blizzard Entertainment, Inc.
defendants:
  - Lilith Games (Shanghai) Co. Ltd.
  - UCool, Inc.
numbers:
  Northern District of California: "3:2015cv04084"
tags:
  - Copyright
  - Open Source
