---
style: DHS v. University of California
plaintiffs:
  - Department of Homeland Security
  - et al
defendants:
  - Regents of the University of California
  - et al
numbers:
  Supreme Court: 18-587
tags:
  - DACA
  - Immigration
