---
style: Sanchez v. Fresno
mnemonic: seizure of homeless property
reports:
  - volume: 914
    reporter: F.Supp.2d
    page: 1079
    year: 2012
    court: Eastern District of California
tags:
  - Homelessness
