---
style: MDY v. Blizzard
mnemonic: Glider leveling bot for World of Warcraft
reports:
  - volume: 629
    reporter: F.3d
    page: 928
tags:
  - Copyright
  - Contract
  - Arizona Law
  - Delaware Law
  - License or Contract
  - Copyright Preclusion
claims:
  - Declaratory Judgment
  - Copyright Infringement
  - DMCA 1201(a)(2)
  - DMCA 1201(b)(1)
  - Tortious Interference with Contract
notes: |
  - EULA for game client
  - terms of service for online service
  - Glider automate play through early World of Warcraft levels
  - Glider does not alter or copy WoW client
  - Blizzard's Warden to prevent connections with modified software
  - Blizzard banned Glider users
  - MDY modified Glider to avoid Warden detection
  - Glider Elite service for extra protection
  - Glider website said it violated Blizzard TOU
  - 120,000 sales, $3.5m gross revenue
  - cease-and-desist
  - MDY asked Blizzard to clarify how install file was infringing
  - Blizzard counsel visited Donnelly's home, threatening suit
  - stipulated $6m judgment
  - playing game creates RAM copy
  - > You agree that you will not ... (ii) create or use cheats, bots, "mods," and/or hacks, or any other third-party softare designed to modify the World of Warcraft experience...
  - cites Vernor v. Autodesk for license-versus-owner
  - cites Sun v. Microsoft: "A copyright owner who grants a nonexclusive, limited license ordinarily waives the right to sue licensees for copyright infringement, and it may sue only for breach of contract."
  - "However, if the licensee acts outside the scope of the license, the licensor may sue for copyrigt infringement."
  - "conditions: breach constitutes copyright infringement"
  - "covenants: breach is actionable only under contract law"
  - > Wherever possible, equity construes ambiguous contract provisions as covenants rather than conditions.
  ## DMCA
  - scan.dll for initial launch
  - resident component for ongoing monitoring
  - 1201(a)(2) v. 1201(b)(1) side-by-side comparison
  - text enough to decide, but covers legislative history
  - > Congress was particularly concerned with encouraging copyright owners to make their works available in digital formats such as "on-demand" or "pay-per-view," which allow consumers effectively to "borrow" a copy of the work for a limited number of uses.
  - declines to follow Federal Circuit's _Chamberlain_ decision (universal garage door openers)
  - cites _Lexmark v. Static Control Components_, 387 F.3d 522 (6th Cir. 2004) (chip to fool Lexmark ink cartridge checks)
  ## Tortious Interference
  - under Arizona law
  ## Copyright Act Preemption
  - cites _Altera Corp. v. Clear Logic, Inc._, 424 F.3d 1079 (9th Cir. 2005) (California law)
  - cites _ProCD_ ("A copyright is a right against the world. Contracts, by contrast, generally affect only their parties; strangers may do as they please, so contracts do not create 'exclusive rights.'")
  - cites Fourth, Fifth, and Eighth Circuit cases agreeing that Copyright Act does not preempt a party's enforcement of its contractual rights
quotes:
  - |
    Were we to hold otherwise, Blizzard --- or any software copyright holder --- could designate any disfavored conduct during softare use as copyright infringement, by purporting to condition the license on the player's abstention from the disfavored conduct.  The rationale would be that because the conduct occurs while the player's computer is copying the software code into RAM in order for it to run, the violation is copyright infringement.  This wouldallow software copyright owners far greater rights than Congress has generally conferred on copyright holders.

    Note 3: A copyright holder may wish to enforce violations of license agreements as copyright infringements for several reasons.  First, breach contract damages are generally limited to the value of actual loss caused by the breach. _See_ 24 Richard A. Lorg, _Williston on Contracts_ § 65:1 (4th ed. 2007).  In contrast, copyright damages include the copyright owner's actual damages and the infringer's actual profits, or statutory damages of up to $150,000 per work.  17 U.S.C. § 504; _see_ _Frank Music Corp. v. MGM, Inc._, 772 F.2d 505, 512 n.5 (9th Cir. 1985).  Second, copyright law offers injunctive relief, seizure of infringing articles, and awards of costs and attorneys' fees. 17 U.S.C. §§ 502-03, 505.  Third, as amicus Software & Information Industry Association highlights, copyright law allows copyright owners a remedy against "downstream" infringers with whom they are not in privity of contract. _See_ _ProCD, Inc._, 86 F.3d at 1454.
holdings:
  - |
    Applying _Vernor_, we hold that WoW players are licensees of WoW's game client software.
  - |
    TOU § 4(B)(ii) and (iii)'s prohibitions against bots and unauthorized third-party software are covenants rather than copyright-enforceable conditions.
  - MDY violated 1201(a)(2) for dynamic, non-literal elements of WoW
  - MDY did not violate 1201(b)(1)
dispositions:
  - remanded for trial on impropriety elements of tortious interference with contract
