---
style: Welte v. Sitecom
mnemonic: first GPL enforcement in Germany
numbers:
  LG Műnchen 1: 21 0 6123/04
documents:
  - date: 2004-05-19
tags:
  - Open Source
  - GPLv2
  - Germany
  - License or Contract
