---
style: Facebook v. Power Ventures
plaintiffs:
  - Facebook, Inc.
defendants:
  - Power Ventures, Inc.
  - Steven Suraj Vachani
court: Northern District of California
number: 5:08-cv-05780
year: 2017
documents:
  - digest: 8f4558d91ef6e1b1d1b201a00170e98425af0d29a7f4149bb1466f10658c37b6
    date: 2016-12-09
    label: opinion
tags:
  - Public Data
  - Platform
  - Terms of Service
  - CFAA
  - CAN-SPAM
  - California Penal Code 502
notes:
  - power.com social media aggregator
  - buton to post promo events, photos, or statuses on Facebook
holdings:
  - Did not violate CAN-SPAM, because messages were not materially misleading.
  - Violated CFAA after receiving cease-and-desist.
  - Violated California Penal Code 502 after receiving cease-and-desist.
quotes:
  - First, a defendant can run afoul of the CFAA when he or she has no permission to access a computer or when such permission has been revoked explicitly. Once permission has been revoked, technological gamesmanship or the enlisting of a third party to aid in access will not excuse liability.
  - Second, a violation of the terms of use of a website—without more—cannot establish liability under the CFAA.
