---
style: Broadcast Music v. CBS
mnemonic: blanket music licenses
plaintiffs:
  - Broadcast Music, Inc.
defendants:
  - Columbia Broadcasting System, Inc.
reports:
  - volume: 441
    reporter: U.S.
    page: 1
courts:
  - Supreme Court
year: 1979
tags:
  - Antitrust
  - Licensing
  - Price Fixing
  - Blanket Licenses
  - ASCAP
  - BMI
notes:
  - American Society of Composers, Authors and Publishers
  - Broadcast Music, Inc.
  - percentage of total revenue or a flat dollar amount
  - below per se illegal
  - below copyright misuse
  - US consent decrees allowed issuing blanket licenses
  - Copyright Acts of 1976 has blanket licenses
  - integration of sales, monitoring, and enforcement
  - difficult and expensive if left to individuals
  - acceptable for a large part of the market
holdings:
  - not price fixing per se
  - rule of reason
