---
style: Triad v. SE Express
plaintiffs:
  - Triad Systems Corp.
defendants:
  - Southeastern Express Corp.
reports:
  - 64 F.3d 1330
courts:
  - 9th Circuit
year: 1995
tags:
  - Copyright
  - First Sale Doctrine
  - 17 USC 177
  - MAI Trio
notes:
  - auto maintenance software
holdings:
  - licensed, not "owner" under first sale or 117
