---
style: Spellman v. SAIS
plaintiffs:
  - Calvin Spellman
defendants:
  - Securities, Annuities and Insurance Services, Inc.
documents:
  - digest: acabc2742cd3d1b4cbe69851c64afb6d4761aea04f20ad91a97999e4eb93ec75
    label: opinion
tags:
  - Incorporation by Reference
  - California
