---
style: National Veterans Legal Services v. US
mnemonic: access to case law
plaintiffs:
  - National Veterans Legal Services Program
  - National Consumer Law Center
  - Alliance for Justice
defendants:
  - United States
numbers:
  - 19-1081
tags:
  - PACER
  - Access to Justice
