---
style: Drauglis v. Kappa
mnemonic: CC-BY-SA photo used as atlas cover
plaintiffs:
  - Art Drauglis
defendants:
  - Kappa Map Group, LLC
numbers:
  D.C. Cir.: No.14-1043 (N.D.DC. Aug. 18, 2015)
year: 2015
tags:
  - Copyright
  - Creative Commons
