---
style: Drauglis v. Kappa
plaintiffs:
  - Art Drauglis
defendants:
  - Kappa Map Group, LLC
courts:
  - District of Columbia
numbers:
  - No.14-1043 (N.D.DC. Aug. 18, 2015)
year: 2015
tags:
  - Copyright
  - Creative Commons
