---
style: Jessop v. Fresno
plaintiffs:
  - Micah Jessop
  - Brittan Ashjian
defendants:
  - City of Fresno
  - Derik Kumagai
  - Curt Chastain
  - Tomas Cantu
courts:
  - 9th Circuit
numbers:
  - 17-16756
tags:
  - Qualified Immunity
  - Fourth Amendment
  - Fourteenth Amendment
notes:
  - cash and coins seized serving warrant on illegal gambling machine operation
holdings:
  - no clearly established violation of fourth amendment
  - no clearly established violation of fourteenth amendment
