---
style: DSC v. Pulse
plaintiffs:
  - DSC Communications Corp.
defendants:
  - Pulse Communications, Inc.
reports:
  - volume: 170
    reporter: F.3d
    page: 1354
courts:
  - Federal Circuit
year: 1999
tags:
  - Copyright
  - First Sale Doctrine
  - 17 USC 177
notes:
  - telecommunications equipment ran software
  - competitor made alternative hardware
  - alternative hardware ran same software
  - criticized MAI
holdings:
  - not "owners" under 117
