---
style: ProCD, Inc. v. Zeidenberg
mnemonic: CD-ROM telephone directory
reports:
  - volume: 908
    reporter: F.Supp.
    page: 640
  - volume: 86
    reporter: F.3d
    page: 1447
numbers:
  7th Circuit
tags:
  - Shrink-Wrap Licenses
  - Copyright
  - Contract
  - Uniform Commercial Code
