---
style: Elasticsearch v. Amazon
mnemonic: trademark against Amazon ES offering
plaintiffs:
  - Elasticsearch, Inc.
defendants:
  - Amazon.com, Inc.
year: 2019
numbers:
  Northern District of California: 5:19-cv-06158
tags:
  - Trademark
  - Open Source
