---
style: Brooke Group v. Brown & Williamson Tobacco
plaintiffs:
  - Brooke Group Ltd.
defendants:
  - Brown & Williamson Tobacco Corp.
courts:
  - Supreme Court
year: 1993
reports:
  - volume: 509
    reporter: U.S.
    page: 209
tags:
  - Antitrust
  - Predatory Pricing
