---
style: Lavan v. LA
menmonic: seizing and destroying unabandoned homeless property
reports:
  - volume: 693
    reporter: F.3d
    page: 1022
    year: 2012
    court: Ninth Circuit
numbers:
  Central District of California: "2:11-cv-02874"
tags:
  - Homelessness
