---
style: Artifex v. Hancom
mnemonic: Ghostscript in Korean word processor
plaintiffs:
  - Artifex Software, Inc.
defendants:
  - Hancom, Inc.
courts:
  - Northern District of California
numbers:
    - 16-cv-06982-JSC (N.D. Cal. Sep. 12, 2017)
tags:
  - Open Source
  - GPL
  - Copyleft
  - License or Contract
  - Copyright
  - Dual Licensing
