---
style: Weyerhaeuser v. Ross-Simmons Hardwood
plaintiffs:
  - Weyerhaeuser Co.
defendants:
  - Ross-Simmons Hardwood Lumber Co.
court: Supreme Court
year: 2007
reports:
  - 549 U.S. 312
tags:
  - Antitrust
  - Predatory Buying
