---
style: Weyerhaeuser v. Ross-Simmons Hardwood
plaintiffs:
  - Weyerhaeuser Co.
defendants:
  - Ross-Simmons Hardwood Lumber Co.
courts:
  - Supreme Court
year: 2007
reports:
  - volume: 549
    reporter: U.S.
    page: 312
tags:
  - Antitrust
  - Predatory Buying
