---
style: Snow v. Eventbrite
mnemonic: no record of UI for accepting TOS with arbitration clause
plaintiffs:
  - Sherri Snow
  - et al
defendants:
  - Eventbrite, Inc.
numbers:
  - "3:20-cv-03698-WHO"
tags:
  - Arbitration
  - Browse-Wrap
  - Click-Wrap
  - Contracts
  - Sign-In-Wrap
  - Terms of Service
documents:
  - date: 2020-10-19
    title: Order Denying Motion to Compel Arbitration
    court: Northern District of California
    holdings:
      - Did not show assent to contract.
