---
style: Snow v. Eventbrite
mnemonic: no record of UI for accepting TOS with arbitration clause
plaintiffs:
  - Sherri Snow
  - et al
defendants:
  - Eventbrite, Inc.
numbers:
  - "3:20-cv-03698-WHO"
tags:
  - Arbitration Clause
  - Browse-Wrap
  - Click-Wrap
  - Contracts
  - Sign-In-Wrap
  - Terms of Service
