---
style: Artifex v. First National
plaintiffs:
  - Artifex Software, Inc.
defendants:
  - First National
courts:
  - Northern District of California
tags:
  - Copyright
  - Open Source
  - Dual Licensing
