---
style: Taylor v. Riojas
mnemonic: prisoner kept naked in freezing, shit-covered cells
tags:
  - Qualified Immunity
  - Prison Conditions
  - Eighth Amendment
documents:
  - date: 2020-11-02
    court: Supreme Court of the United Staees
    holdings:
      - No qualified immunity
