---
style: Lasercomb v. Reynolds
plaintiffs:
  - Lasercomb America, Inc.
defendants:
  - Reynolds
courts:
  - 4th Circuit
year: 1990
reports:
  - 911 F.2d 970
tags:
  - Copyright
  - Copyright Misuse
  - Software
notes:
  - steel rule die software
holdings:
  - copyright misuse
