---
style: Krause v. Tileserv
plaintiffs:
  - Krause
defendants:
  - Titleserv, Inc.
reports:
  - volume: 402
    reporter: F.3d
    page: 119
courts:
  - 2nd Circuit
year: 2005
tags:
  - Copyright
  - First Sale Doctrine
  - 17 USC 177
notes: |
  - developed software under consulting agreement
  - license to use, but not modify
  - followed DSC, not MAI
holdings:
  - not "owner" under 117
