---
style: US v. Wise
plaintiffs:
  - United States
defendants:
  - Wise
reports:
  - volume: 550
    reporter: F.2d
    page: 1180
court: 9th Circuit
year: 1977
tags:
  - Copyright
  - First Sale Doctrine
notes: |
  - mail order film company
  - resale of licensed copies
  - licensed "for limited purposes"
holdings:
  - not first sales
