---
style: US v. Wise
plaintiffs:
  - United States
defendants:
  - Wise
reports:
  - 550 F.2d 1180
court: 9th Circuit
year: 1977
tags:
  - Copyright
  - First Sale Doctrine
notes:
  - mail order film company
  - resale of licensed copies
  - licensed "for limited purposes"
holdings:
  - not first sales
