---
style: PMI v. AMA
plaintiffs:
  - Practice Management Information Corporation
defendants:
  - The American Medical Association
courts:
  - 9th Circuit
year: 1997
reports:
  - volume: 121
    reporter: F.3d
    page: 516
tags:
  - Copyright
  - Copyright Misuse
  - Software
notes: |
  - medical coding system
holdings:
  - copyright misuse
