---
style: Capitol Records v. ReDigi
plaintiffs:
  - Capitol Records, LLC
defendants:
  - ReDigi Inc.
courts:
  - Southern District of New York
numbers:
  - "12-cv-95"
tags:
  - Copyright
notes:
  - biased introductions of parties
  - sell legally acquired music files online
  - Music Manager deletes copies on transfer
  - had license for previews and cover art, but lost it
  - reproduction on fixation in new material object
  - reproduction as right to embody
  - cites P2P cases for hard drive embodiment
  - 'Cites C.M. Paula Co. v. Logan: used chemicals to lift images off of greeting cards'
  - calls Logan "questionable"
  - argument about moving on hard drive a "red herring" because subject of other doctrines and defenses
  - fair use an "equitable rule of reason"
  - fair use limited to distribution
  - no first sale because copies not lawfully made
  - cites Copyright Office DMCA report with deference
  - "Seciton 109(a) still protects a lawful owner's sale of her 'particular' phonorecord, be it a computer hard disk, iPod, or other memory device onto which the file was originally downloaded."
  - Cites Cartoon Network v. CSC Holdings, 536 F.3d 121 (2d Cir. 2008)
  - "The Legal Alternative"
  - "YES, ReDigi is LEGAL."
  - "the law cannot be said to be well-settled"
  - "researched copyright law [and] consulted with attorneys"
  - "declined to reveal any of the advice it received on the subject"
quotes:
  - "fundamental clash over culture, policy, and copyright law"
  - "this is a court of law and not a congressional subcommittee or technology blog"
  - '"Cloud Locker." an ethereal monicker for what is, in fact, merely a remote server in Arizona'
  - "The novel question presented in this action is whether a digital music file, lawfully made and purchased, may be resold by its owner through ReDigi under the first sale doctrine. The Court determines that it cannot."
  - "only one file exists before and after the transfer"
  - "It is simply implossible that the same 'material object' can be transferred over the Internet."
  - "It is beside the point that the original phonorecord no longer exists. It matters only that a new phonorecord has been created."
  - "Each of the statutory [fair use] factors counsels against a finding of fair use."
  - "ReDigi incredibly argues that Capitol is preempted from making a market-based argument because Capitol itself condones downloading of its work on iTunes."
  - "Because it is therefore impossible for the user to sell her 'particular' phonorecord on ReDigi, the first sale statute cannot provide a defense."
  - "First, while technological change may have rendered Section 109(a) unsatisfactory to many contemporary observers and consumers, it has not rendered it ambiguous."
  - "amendment of the Copyright Act in line with ReDigi's proposal isa legislative prerogative that courts are unauthorized and ill suited to attempt"
  - "While the process itself is automated, absolving ReDigi of direct liability on that ground alone would be a distinction without a difference."
  - "Media Manager ensured that _only_ infringement occurred by limiting eligible files to iTunes tracks."
  - "Accordingly, to comply with the law, either the law or ReDigi must change."
  - "ReDigi seeks judicial amendment ofthe Copyright Act to reach its desired policy outcome"
  - "the Court cannot of its own accord condone the wholesale application fo the first sale defense to the digital sphere, particularly when Congress itself has declined to take that step."
claims:
  - Copyright Infringement
holdings:
  - infringed reproduction right
  - infringed distribution right
  - material fact disputes on performance and display
  - direct infringement
  - secondary infringement
  - contributory infringement
  - vicarious infringement
