---
style: Pearson v. Callahan
mnemonic: undercover police admitted into house find drugs
numbers:
   Supreme Court: 07-751
reports:
  - date: 2009-01-21
    notes: |
      - held: did not violate clearly established law
      - held: entitled to qualified immunity
tags:
  - Qualified Immunity
  - 42 USC 1983
  - Consent-Once-Removed Doctrine
