---
style: Great Minds v. FedEx
mnemonic: CC-BY-NC course packet at copy shop
plaintiffs:
  - Great Minds
defendants:
  - FedEx Office and Print Services, Inc.
numbers:
  - "16-CV-1462"
tags:
  - Copyright
  - Creative Commons
