---
style: US v. Moalin
plaintiffs:
  - United States
defendants:
  - Basaaly Saeed Moalin
courts:
  - 9th Circuit
numbers:
  - "13-50572"
tags:
  - National Security
  - National Security Agency
  - Surveillance
  - FISA
  - Fourth Amendment
