---
style: US v. Moalin
plaintiffs:
  - United States
defendants:
  - Basaaly Saeed Moalin
numbers:
  9th Circuit: "13-50572"
tags:
  - National Security
  - National Security Agency
  - Surveillance
  - FISA
  - Fourth Amendment
