---
style: Wall Data v. LA Sheriff's
plaintiffs:
  - Wall Data, Inc.
defendants:
  - Los Angeles County Sheriff's Department
reports:
  - volume: 447
    reporter: F.3d
    page: 769
court: 9th Circuit
year: 2006
tags:
  - Copyright
  - First Sale Doctrine
  - 17 USC 177
  - MAI Trio
notes:
  - volume license exceeded
holdings:
  - licensed, not "owner" under first sale or 117
