---
style: Chan v. Drexel Burnham Lambert
plaintiffs:
  - Adra K. Chan
defendants:
  - Drexel Burnham Lambert, Incorporated
documents:
  - digest: 808ce5b60ac79526babbcc080275298c6c181dafb53039ba05c927a97d62587f
    label: opinion
tags:
  - Incorporation by Reference
  - California
